# Generated by Django 5.0.4 on 2024-04-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='kelly_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='odd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='teams',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='check',
            name='match_number',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='check',
            name='user',
            field=models.TextField(default='-'),
        ),
    ]
