# Generated by Django 5.0.4 on 2024-04-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_check_amt_check_cash_check_kelly_rate_check_odd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(default='-')),
                ('date', models.TextField(default='-')),
                ('end_time', models.TextField(default='-')),
                ('home_team', models.TextField(default='-')),
                ('away_team', models.TextField(default='-')),
                ('odd_list', models.TextField(default='-')),
                ('prob_from_odd_list', models.TextField(default='-')),
            ],
        ),
    ]
