# Generated by Django 5.0.4 on 2024-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_matchdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdb',
            name='betting_type',
            field=models.TextField(default='-'),
        ),
    ]
