# Generated by Django 5.0.4 on 2024-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_matchdb_betting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDB_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(default='-')),
                ('date', models.TextField(default='-')),
                ('end_time', models.TextField(default='-')),
                ('betting_type', models.TextField(default='-')),
                ('home_team', models.TextField(default='-')),
                ('away_team', models.TextField(default='-')),
                ('odd_list', models.TextField(default='-')),
                ('prob_from_odd_list', models.TextField(default='-')),
            ],
        ),
    ]
