# Generated by Django 5.0.4 on 2024-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_matchdb_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdb',
            name='betting_sports',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='matchdb',
            name='league_name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='matchdb_one',
            name='betting_sports',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='matchdb_one',
            name='league_name',
            field=models.TextField(default='-'),
        ),
    ]
