# Generated by Django 5.0.4 on 2024-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_matchdb_betting_sports_matchdb_league_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdb',
            name='handicap_value',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='matchdb',
            name='under_over_value',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='matchdb_one',
            name='handicap_value',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='matchdb_one',
            name='under_over_value',
            field=models.TextField(default=0),
        ),
    ]
